### ISSUE TITLE
Is JS needed ?

### ISSUE THREAD

**Issue by sebilasse** [matthiasott/a11y-accordion-tabs#1]
We can easily achieve the same functionality with only HTML / CSS :
https://codepen.io/sebilasse/pen/qjxQjp
But how about a11y then ?
Most important : Happy holidays ! 🎄

**Comment by matthiasott** [comment]
Hi Sebi! A late answer, but better late than never. Yes, as you already wrote, JS is needed because I set the aria-roles and tabindex attributes with it. That's the whole point of the component. ;)
